name: Run Playwright @smoke and @regression tests on PR or trigger them manually

on:
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  # Stage 1: Smoke tests
  smoke:
    runs-on: ubuntu-latest
    name: Run Smoke Tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: npx playwright test --grep @smoke

  # Stage 2: Regression tests
  regression:
    runs-on: ubuntu-latest
    name: Run Regression Tests
    needs: smoke # only runs if "smoke" job succeeds
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Regression Tests
        run: npx playwright test --grep @regression